"""Add settings model

Revision ID: a41b89dfad4c
Revises: 52c317a35e2a
Create Date: 2026-08-22 13:53:23.795008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41b89dfad4c'
down_revision: Union[str, Sequence[str], None] = '52c317a35e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.String(length=500), nullable=True),
    sa.Column('working_hours', sa.String(length=100), nullable=True),
    sa.Column('allow_employee_registration', sa.Boolean(), nullable=True),
    sa.Column('require_approval_for_leaves', sa.Boolean(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
